name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action: #can be any name as its a description of your job
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event)}}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}    #comments on a particlar issue after we pass the number on it
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'  