#Name of our workflow
name: Deploy AWS Lambda
#Section that defines when our workflow actually runs
on:
    push:
      branches:
        - main
      paths:
        - 'lambda/**'

jobs: 
    deploy-lambda: #name of our job
        runs-on: ubuntu-latest # Sets or specifies the runner
        steps:
        - uses: actions/checkout@v2

        - name: Set up Python # Sets up python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'

        - name: Install Dependencies #Installs dependencies if any
          run: |
            python -m pip install --upgrade pip
            pip install -r  lambda/requirements.txt -t lambda/

        - name: Configure AWS Credentials #Sets up AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY-ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2

        - name: Deploy Lambda Function #Zips Lambda and updates lambda function
          run: |
            cd lambda
            zip -r lambda.zip
            aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip

        